### ISSUE TITLE
Incorrect usage of command key causes bootstrap.sh to never run

### ISSUE THREAD

**Issue by jeremyjpaws** [avattathil/cfn-authenticated-s3-example#1]
The command key is not valid under a files section. A config command section requires a new code block after the files block.

Error is at this line. Note the given command will never run, as can be seen by lack of output into `/var/log/cfn-init.log` and `cfn-init-cmd.log` during testing:
* https://github.com/tonynv/cfn-authenticated-s3-example/blob/master/templates/authenticated-s3.template.yaml#L188

See how command key is absent for valid keys under files block at:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-files

Suggested correction, see commands block:

```
helloworld_cfg:
          files:
            /tmp/bootstrap.sh:
              source: !Sub
                - >-
                  https://${BucketName}.${S3Region}.amazonaws.com/${KeyPrefix}scripts/print_stdout.sh
                - BucketName: !Ref BucketName
                  S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, !Sub 's3.${AWS::Region}' ]
                  KeyPrefix: !Ref KeyPrefix
              mode: '000755'
              owner: root
              group: root
              authentication: S3AccessCreds
          commands: 
            test: 
              command: "/tmp/bootstrap.sh helloworld"
              ignoreErrors: "false"
```
